### ISSUE TITLE
Easy mode for all quests

### ISSUE THREAD

**Issue by sappidus** [seastan/DragnCards#16]
At this time, it seems that the easy-mode versions of FFG quests are not available past a certain point (Raid on the Grey Havens?). Easy mode has historically been a bit marginalized in the life of the game, but DragnCards offers an opportunity for more players to easily (no pun intended) try it out. In particular, some of the tough quests from the Vengeance of Mordor cycle may find some extra life from something less frankly punishing than normal mode, at least for certain individuals and/or groups.

**Comment by seastan** [comment]
I agree. The only thing that prevents me from having this already is the time commitment. But if someone is interested in helping out, here is what they could do:

1. Check out this repo: https://github.com/seastan/Lord-of-the-Rings/tree/master/o8g/Decks/Quests
2. Go into a directory for a cycle that does not have easy mode, like Q07-The-Sands-of-Harad-Haradrim
3. Create a directory called "Easy"
4. Copy all the quests from the cycle into the Easy directory
5. Rename the files to start with an E instead of a Q (you can can look at a directory for a cycle that has Easy mode already for guidance) 
6. Open up each easy quest file with a standard text editor and make the necessary adjustments for easy mode.
7. Create a pull request once finished

After I merge the pull request, these quests would automatically appear in DragnCards.

It's a fair amount of work, but I'd be happy to give the individual that does this permanent supporter status on DragnCards if they don't already have it.

**Comment by seastan** [comment]
Easy mode quests for all quests are now live on DragnCards. Thanks @slester!

**Comment by djpangxie** [comment]
It's a gospel.

**Comment by djpangxie** [comment]
That's a real boon!
